dist: bionic

language: node_js
node_js:
  - "10"

before_install:
  - sudo add-apt-repository -y ppa:savoury1/backports
  - sudo apt-get -q update
  - sudo apt-get -y install curl

before_script:
  - curl --version
  - curl http://overpass-api.de/api/status

script:
  - make --jobs=4 USER_AGENT="github.com/awendt/familienradwege"

deploy:
  provider: s3
  bucket: familienradwege
  region: eu-central-1
  local_dir: dist/berlin
  upload-dir: data/berlin
  acl: public_read
  skip_cleanup: true
  on: master
