sudo: false

language: node_js
node_js:
  - node # latest stable Node.js release

cache:
  directories:
  - dist

script:
  - ls -laR dist
  - make
  - ls -laR website

deploy:
  provider: surge
  project: ./website/
  domain: different-shoe.surge.sh
  skip_cleanup: true
  on: automate
