sudo: false

language: node_js
node_js:
  - node # latest stable Node.js release

cache:
  directories:
  - node_modules # NPM packages
  - dist

script:
  - ls -laR dist
  - make
  - ls -laR website
