sudo: false

language: node_js
node_js:
  - node # latest stable Node.js release

cache:
  directories:
  - dist

script:
  - make USER_AGENT="Travis build for github.com/awendt/familienradwege"

deploy:
  provider: surge
  project: ./website/
  domain: different-shoe.surge.sh
  skip_cleanup: true
  on: automate
