dist: bionic

language: node_js
node_js:
  - "10"

cache:
  directories:
  - cache

before_script:
  - curl http://overpass-api.de/api/status

script:
  - make --jobs=2 VERBOSE=1 REFRESH=2 CACHE_DIR=cache USER_AGENT="github.com/awendt/familienradwege"

deploy:
  provider: s3
  bucket: familienradwege
  region: eu-central-1
  local_dir: dist/berlin
  upload-dir: data/berlin
  acl: public_read
  skip_cleanup: true
  on: master
