name: build-json-files

on:
  pull_request:

  push:
    branches:
      - master

  schedule:
    - cron:  '0 7 * * FRI'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Show API status
      run: curl http://overpass-api.de/api/status
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build JSON files
      run: make build --jobs=2 USER_AGENT="github.com/awendt/familienradwege"

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  verify:
    needs: build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Fake-build all missing files
      run: mkdir -p tmp && find dist -type f | xargs make --touch
    - name: Verify JSON files
      run: make verify --jobs=2

  upload:
    if: github.ref == 'refs/heads/master'
    needs: verify
    runs-on: ubuntu-20.04

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
      run: aws s3 cp dist s3://familienradwege/data --acl public-read --recursive --exclude "*" --include "*.json"
