name: build-json-files

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Show API status
      run: curl http://overpass-api.de/api/status
    - name: Build JSON files
      run: make all --jobs=4 USER_AGENT="github.com/awendt/familienradwege"
    - name: Verify JSON files
      run: make verify
